import { GalleryItem } from "@/types/gallery";

export const GALLERY_ITEMS: readonly GalleryItem[] = [
  {
    id: "gal-1",
    title: "Classroom Reading & Phonics Session",
    description: "Young learners engaged in guided storytelling and reading fundamentals.",
    imageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop",
    category: "classrooms",
    altText: "Teacher guiding students during reading session",
    isPlaceholder: true,
  },
  {
    id: "gal-2",
    title: "Creative Arts & Drawing Circle",
    description: "Developing fine motor coordination and creative imagination with colors.",
    imageUrl: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=1200&auto=format&fit=crop",
    category: "activities",
    altText: "Children drawing and painting on art paper",
    isPlaceholder: true,
  },
  {
    id: "gal-3",
    title: "Kindergarten Interactive Play & Blocks",
    description: "Foundational numeracy and shape exploration through structured block play.",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1200&auto=format&fit=crop",
    category: "classrooms",
    altText: "Kindergarten students exploring educational blocks",
    isPlaceholder: true,
  },
  {
    id: "gal-4",
    title: "Outdoor Recreation & Physical Games",
    description: "Supervised play supporting agility, healthy exercise, and teamwork.",
    imageUrl: "https://images.unsplash.com/photo-1576267423445-b2e0074d68a4?q=80&w=1200&auto=format&fit=crop",
    category: "campus",
    altText: "Students enjoying supervised outdoor activities",
    isPlaceholder: true,
  },
  {
    id: "gal-5",
    title: "Primary Grade Mathematics & Inquiry",
    description: "Step-by-step arithmetic comprehension and problem solving.",
    imageUrl: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?q=80&w=1200&auto=format&fit=crop",
    category: "classrooms",
    altText: "Primary grade students in focused classroom study",
    isPlaceholder: true,
  },
  {
    id: "gal-6",
    title: "School Library & Quiet Reading Space",
    description: "Fostering an early love for books in a calm, ventilated environment.",
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop",
    category: "campus",
    altText: "Children reading books in the school library corner",
    isPlaceholder: true,
  },
  {
    id: "gal-7",
    title: "Annual Celebration & Cultural Performance",
    description: "Celebrating festivals and student performances on stage.",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop",
    category: "celebrations",
    altText: "Students participating in school cultural celebration",
    isPlaceholder: true,
  },
  {
    id: "gal-8",
    title: "Collaborative Science & Nature Exploration",
    description: "Observing natural surroundings and environmental curiosity.",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1200&auto=format&fit=crop",
    category: "activities",
    altText: "Children engaged in active group discovery",
    isPlaceholder: true,
  },
] as const;
